### PR TITLE
add support for custom template bridge

### PR DESCRIPTION
**Pull request by Bizordec**
Add support for custom template bridge that can be set by `template_bridge` setting in `conf.py` (https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-template_bridge)

### CODE REVIEW

**Comment by dhellmann** [comment]
This looks OK, but I don't know how I would use a custom template bridge. What's that for? Is there a (relatively painless) way to add a test?

**Comment by Bizordec** [comment]
Custom template bridge would allow to add **custom filters** for templates. I've added a test to demonstrate this.

Although I had to move `tests` dir to the root to make `pytest_plugins` config option work (https://docs.pytest.org/en/7.1.x/how-to/plugins.html#requiring-loading-plugins-in-a-test-module-or-conftest-file).

**Comment by Bizordec** [comment]
Custom template bridge would allow to add **custom filters** for templates. I've added a test to demonstrate this.

Although I had to move `tests` dir to the root to make `pytest_plugins` config option work (https://docs.pytest.org/en/7.1.x/how-to/plugins.html#requiring-loading-plugins-in-a-test-module-or-conftest-file).

**Comment by dhellmann** [comment]
The change looks generally good, thanks for adding the test and explaining exactly what it's for. It looks like there are a couple of issues with the tests on older versions of Python that are still supported.

**Comment by Bizordec** [comment]
Fixed

**Review by dhellmann — APPROVED** [review]
Thanks!

**Comment by dhellmann** [comment]
This feature is included in the 0.10.2 release that was just published. Thank you again for your contribution!

**Pull request merged**
