### PR TITLE
add html_context to template context

### PR DESCRIPTION
**Pull request by dhellmann**
Pass the global html_context set in conf.py to templates as they are
rendered. This allows users to set "globals" across their project that
will effect all of the templates. It also allows users to set
page-specific values dynamically, using the html-page-context event.

### CODE REVIEW

**Comment by dhellmann** [comment]
This supersedes #5

**Comment by janbrohl** [comment]
Why not pass either a new variable `datatemplate_context` set in `config.py` or all of `app.config`?

**Comment by dhellmann** [comment]
> Why not pass either a new variable `datatemplate_context` set in `config.py` or all of `app.config`?

We could do that, too. I pretty regularly use the event hook to add things to the HTML context so I was focused on that.

How about if we add those other things as separate PRs?

**Comment by janbrohl** [comment]
With extra PRs we would have to either remove `html_context` or have it available twice - to me it seems much easier to just pass `app.config` to the template as `config` and use `config.html_context` instead.

**Review by janbrohl — APPROVED** [review]
Looks good to me.

**Comment by dhellmann** [comment]
> With extra PRs we would have to either remove `html_context` or have it available twice - to me it seems much easier to just pass `app.config` to the template as `config` and use `config.html_context` instead.

I see what you mean. OK, I will rework this to pass the config instead.

I wonder if the HTML context modified by the event handler is the same as the one in the config. I'll have to test that.

**Review by janbrohl — APPROVED** [review]
Great

**Pull request merged**
