### PR TITLE
set up unit test framework

### LINKED ISSUE #58: set up unit test framework
We need more automation for testing.

### PR DESCRIPTION
**Pull request by dhellmann**
Fixes #58

### CODE REVIEW

**Comment by dhellmann** [comment]
After we land this, we can expand the test suite to cover more cases.

**Comment by janbrohl** [comment]
Is there a way to not use shell scripts? They are broken on my Windows machine.

**Review by janbrohl — COMMENTED** [review]
Is there a way to not use shell scripts? They are broken on my Windows machine

**Comment by dhellmann** [comment]
> Is there a way to not use shell scripts? They are broken on my Windows machine

Sure, I can rework this.

**Comment by dhellmann** [comment]
> > Is there a way to not use shell scripts? They are broken on my Windows machine
> 
> Sure, I can rework this.

Done

**Review by janbrohl — APPROVED** [review]
LGTM

**Pull request merged**
