### PR TITLE
docs: update use instructions

### LINKED ISSUE #75: How to install datatemplates extension?
Hello, 

Thank you for your work. There is no instruction on how to install this extension, even in the manual.

I am struggling to make it work with a very simple JSON inline example.

1. I installed the extension: `pip install sphinxcontrib.datatemplates`
2. I added the extension to `conf.py`:
    ```python
       extensions = [
        #other extensions...
        "sphinxcontrib.datatemplates"
     ```
3.  I created a `test.json` file:
```json
{
   "allo": "test"
}

```
4. I included in a rst file:
```rst
.. datatemplate:json::
   :source: test.json

Toto
----

{{ data['allo'] }}

``` 

The Sphinx documentation builds printing the raw instruction `{{ data['allo'] }}` instead of `test`.

### LINKED ISSUE #76: Where should be put template files?
Trying to debug #75 , I have created a simple example with in the same folder

- an RST file `test.rst`
```rst
.. datatemplate:json:: test.json
   :template: ./test.tmpl
```
- a JSON file `test.json`
```
{
   "allo": "test"
}

```
- a template `test.tmpl`
```
Test
~~~~

{{ data['allo'] }}

```
I get this error in the log when building Sphinx
```
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./test.tmpl
```

This indicates jinja2 does not find the template. Where should the template be put? This point is not mentionned in the doc.

Thanks in advance,

### PR DESCRIPTION
**Pull request by dhellmann**
Fixes #75
Fixes #76

### CODE REVIEW

**Comment by dhellmann** [comment]
@kevung Do these changes answer your questions?

**Comment by kevung** [comment]
Hello and thanks for your pull request!  These changes answer fully my answers and I could succeed to use a template with datatemplates.

**Comment by dhellmann** [comment]
> Hello and thanks for your pull request! These changes answer fully my answers and I could succeed to use a template with datatemplates.

Excellent, thank you for helping by reviewing the documentation changes.

**Review by janbrohl — COMMENTED** [review]
Looks good.

**Pull request merged**
